let challenge = '30 Days Of JavaScript'
console.log (challenge)
console.log (challenge.length)
console.log (challenge.toUpperCase())
console.log (challenge.toLowerCase())
console.log (challenge.substring(0,2))
console.log (challenge.includes('Script'))
console.log (challenge.split(" "))
console.log ('Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'.split(','))
console.log (challenge.replace('JavaScript', 'Node'))
console.log (challenge.charAt(15))
console.log (challenge.charCodeAt('J'))
console.log (challenge.indexOf('a'))
console.log (challenge.lastIndexOf('a'))
console.log ('You cannot end a sentence with because because because is a conjunction'. indexOf('because'))
console.log ('You cannot end a sentence with because because because is a conjunction'. lastIndexOf('because'))
console.log ('You cannot end a sentence with because because because is a conjunction'. search('because'))
console.log (challenge.startsWith('30'))
console.log (challenge.endsWith('t'))
console.log (challenge.match('a'))
console.log ('30 Days Of'.concat(' JavaScript'))
console.log (challenge.repeat(2))